# Generated by Django 5.2.4 on 2025-07-18 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feedlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedlike',
            name='unique_post_user_like',
        ),
        migrations.AlterUniqueTogether(
            name='feedlike',
            unique_together={('post', 'user')},
        ),
    ]
