# Generated by Django 5.2.4 on 2025-07-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
